import { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  ActivityIndicator,
  RefreshControl,
} from 'react-native';
import { useTravelProfile } from '../../src/hooks/useTravelProfile';
import { useAuth } from '../../src/hooks/useAuth';

const PACE_LABELS: Record<string, string> = {
  relaxed: '🏖️ Relaxed',
  moderate: '🗺️ Moderate',
  packed: '⚡ Packed',
};

const ACCOMMODATION_LABELS: Record<string, string> = {
  budget: 'Budget-friendly',
  boutique: 'Boutique',
  luxury: 'Luxury',
};

const TAG_COLORS: Record<string, string> = {
  'food-first': '#FF6B6B',
  adventure: '#4ECDC4',
  luxury: '#FFD93D',
  budget: '#6BCB77',
  culture: '#9B59B6',
  photography: '#E67E22',
  hiking: '#27AE60',
  beach: '#3498DB',
  'slow-travel': '#1ABC9C',
};

export default function ProfileScreen() {
  const { user } = useAuth();
  const { profile, recentRatings, personality, loading, refetch } = useTravelProfile();
  const [aiPersonality, setAiPersonality] = useState('');

  useEffect(() => {
    if (personality) setAiPersonality(personality);
  }, [personality]);

  function getTagColor(tag: string): string {
    return TAG_COLORS[tag] || '#0D6B6B';
  }

  const totalTravelDays = 0; // Could calculate from trip durations

  return (
    <ScrollView
      style={styles.container}
      refreshControl={
        <RefreshControl refreshing={loading} onRefresh={refetch} tintColor="#0D6B6B" />
      }
    >
      <View style={styles.header}>
        <Text style={styles.headerTitle}>My Profile</Text>
      </View>

      {loading && !profile ? (
        <ActivityIndicator size="large" color="#0D6B6B" style={{ marginTop: 40 }} />
      ) : profile ? (
        <>
          {/* Stats Cards */}
          <View style={styles.statsRow}>
            <View style={styles.statCard}>
              <Text style={styles.statNumber}>{profile.total_trips || 0}</Text>
              <Text style={styles.statLabel}>Trips</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statNumber}>
                {profile.countries_visited?.length || 0}
              </Text>
              <Text style={styles.statLabel}>Countries</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statNumber}>{totalTravelDays}</Text>
              <Text style={styles.statLabel}>Travel Days</Text>
            </View>
          </View>

          {/* Travel style tags */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Travel Style</Text>
            <View style={styles.tagContainer}>
              {profile.travel_style_tags?.map((tag) => (
                <View
                  key={tag}
                  style={[styles.tag, { backgroundColor: getTagColor(tag) + '20', borderColor: getTagColor(tag) }]}
                >
                  <Text style={[styles.tagText, { color: getTagColor(tag) }]}>
                    {tag.replace(/-/g, ' ')}
                  </Text>
                </View>
              ))}
            </View>
          </View>

          {/* Preferences */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Preferences</Text>

            <View style={styles.prefCard}>
              <Text style={styles.prefLabel}>Trip Pace</Text>
              <Text style={styles.prefValue}>
                {PACE_LABELS[profile.trip_pace] || profile.trip_pace}
              </Text>
            </View>

            <View style={styles.prefCard}>
              <Text style={styles.prefLabel}>Accommodation</Text>
              <Text style={styles.prefValue}>
                {ACCOMMODATION_LABELS[profile.preferred_accommodation] || profile.preferred_accommodation}
              </Text>
            </View>

            {profile.interests?.length > 0 && (
              <View style={styles.prefCard}>
                <Text style={styles.prefLabel}>Interests</Text>
                <Text style={styles.prefValue}>
                  {profile.interests.join(', ')}
                </Text>
              </View>
            )}
          </View>

          {/* AI Personality */}
          {aiPersonality ? (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Your Travel Personality</Text>
              <View style={styles.personalityCard}>
                <Text style={styles.personalityText}>{aiPersonality}</Text>
                <Text style={styles.personalityFooter}>
                  Generated by AI based on your travel history
                </Text>
              </View>
            </View>
          ) : null}

          {/* Recent Ratings */}
          {recentRatings.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Recent Trip Ratings</Text>
              {recentRatings.map((rating) => (
                <View key={rating.id} style={styles.ratingCard}>
                  <View style={styles.ratingStars}>
                    {[1, 2, 3, 4, 5].map((star) => (
                      <Text key={star} style={styles.star}>
                        {star <= rating.overall_rating ? '★' : '☆'}
                      </Text>
                    ))}
                  </View>
                  {rating.notes && (
                    <Text style={styles.ratingNotes}>{rating.notes}</Text>
                  )}
                </View>
              ))}
            </View>
          )}

          {/* Countries visited */}
          {profile.countries_visited?.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Countries Visited</Text>
              <View style={styles.countryList}>
                {profile.countries_visited.map((country) => (
                  <View key={country} style={styles.countryChip}>
                    <Text style={styles.countryText}>{country}</Text>
                  </View>
                ))}
              </View>
            </View>
          )}
        </>
      ) : (
        <View style={styles.emptyState}>
          <Text style={styles.emptyTitle}>No profile yet</Text>
          <Text style={styles.emptyDesc}>
            Complete the travel quiz or add your first trip to build your profile
          </Text>
        </View>
      )}

      <View style={{ height: 40 }} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: 24,
    paddingBottom: 16,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#222',
  },
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  statNumber: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0D6B6B',
  },
  statLabel: {
    fontSize: 12,
    color: '#999',
    marginTop: 4,
    fontWeight: '600',
  },
  section: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    marginBottom: 12,
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tag: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  tagText: {
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  prefCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  prefLabel: {
    fontSize: 14,
    color: '#666',
  },
  prefValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#222',
  },
  personalityCard: {
    backgroundColor: '#E8F5F5',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#B8D8D8',
  },
  personalityText: {
    fontSize: 15,
    color: '#333',
    lineHeight: 22,
    fontStyle: 'italic',
  },
  personalityFooter: {
    fontSize: 11,
    color: '#999',
    marginTop: 12,
  },
  ratingCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
  },
  ratingStars: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  star: {
    fontSize: 18,
    color: '#F5A623',
  },
  ratingNotes: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },
  countryList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  countryChip: {
    backgroundColor: '#F0F0F0',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
  },
  countryText: {
    fontSize: 13,
    color: '#555',
    fontWeight: '500',
  },
  emptyState: {
    alignItems: 'center',
    paddingTop: 80,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    marginBottom: 8,
  },
  emptyDesc: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    paddingHorizontal: 40,
  },
});
